spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb
#      database: userdb

server:
  port: 8082

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG

#mongodb+srv://amansrivastav1825_db_user:58064eCQpqioUCmk@user-data.frtuwtt.mongodb.net/?retryWrites=true&w=majority&appName=user-data
#  58064eCQpqioUCmk